# Generated by Django 2.2.16 on 2022-11-12 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20221112_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть равно 0')], verbose_name='Время приготовления в минутах'),
        ),
    ]
