# Generated by Django 2.2.16 on 2022-11-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221106_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=16, null=True),
        ),
    ]
